### ISSUE TITLE
리스트 추가 요청입니다

### ISSUE THREAD

**Issue by K-AVLB** [devinan/nomadstudy-github-list#35]
**NomadCoders Profile:** https://nomadcoders.co/users/mdj970930
**Slack Nickname:** snailmin
**Nomad Study 기수:**  1기

**Comment by devinan** [comment]
안녕하세요 @K-AVLB  님, 한국시간 오늘 오후 7시에 master 브런치로 등록 하겠습니다.
노마드 스터디 깃헙 리스트에 추가 요청해주셔서 감사합니다.🥳

**Comment by juninjune** [comment]
NomadCoders Profile: https://nomadcoders.co/users/r0otstat1c
Slack Nickname: 전석희
Nomad Study 기수: 1기
